<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'vich_uploader.file_injector' shared service.

include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Injector/FileInjectorInterface.php';
include_once $this->targetDirs[3].'/vendor/vich/uploader-bundle/Injector/FileInjector.php';

return $this->privates['vich_uploader.file_injector'] = new \Vich\UploaderBundle\Injector\FileInjector(($this->privates['vich_uploader.storage.file_system'] ?? $this->getVichUploader_Storage_FileSystemService()));
