<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iW_buO_' shared service.

return $this->privates['.service_locator.iW_buO_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'partenaire' => ['privates', '.errored..service_locator.iW_buO_.App\\Entity\\Partenaire', NULL, 'Cannot autowire service ".service_locator.iW_buO_": it references class "App\\Entity\\Partenaire" but no such service exists.'],
    'partenaireRepository' => ['privates', 'App\\Repository\\PartenaireRepository', 'getPartenaireRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'partenaire' => 'App\\Entity\\Partenaire',
    'partenaireRepository' => 'App\\Repository\\PartenaireRepository',
    'serializer' => '?',
]);
