<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ndYZ51c' shared service.

return $this->privates['.service_locator.ndYZ51c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ApiController::ajoutp' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController::bloquerdebloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\ApiController::depot' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController::register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController::show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\ApiController::superadmin' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController::update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
    'App\\Controller\\ApiController:ajoutp' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController:bloquerdebloquer' => ['privates', '.service_locator.U2OyWts', 'get_ServiceLocator_U2OyWtsService.php', true],
    'App\\Controller\\ApiController:depot' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController:register' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController:show' => ['privates', '.service_locator.iW_buO_', 'get_ServiceLocator_IWBuOService.php', true],
    'App\\Controller\\ApiController:superadmin' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\ApiController:update' => ['privates', '.service_locator.fDbIXxi', 'get_ServiceLocator_FDbIXxiService.php', true],
], [
    'App\\Controller\\ApiController::ajoutp' => '?',
    'App\\Controller\\ApiController::bloquerdebloquer' => '?',
    'App\\Controller\\ApiController::depot' => '?',
    'App\\Controller\\ApiController::register' => '?',
    'App\\Controller\\ApiController::show' => '?',
    'App\\Controller\\ApiController::superadmin' => '?',
    'App\\Controller\\ApiController::update' => '?',
    'App\\Controller\\ApiController:ajoutp' => '?',
    'App\\Controller\\ApiController:bloquerdebloquer' => '?',
    'App\\Controller\\ApiController:depot' => '?',
    'App\\Controller\\ApiController:register' => '?',
    'App\\Controller\\ApiController:show' => '?',
    'App\\Controller\\ApiController:superadmin' => '?',
    'App\\Controller\\ApiController:update' => '?',
]);
