<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6U5sZxG\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6U5sZxG/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container6U5sZxG.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container6U5sZxG\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container6U5sZxG\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '6U5sZxG',
    'container.build_id' => 'f204d4f2',
    'container.build_time' => 1565020707,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6U5sZxG');
