<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1Vhb2As\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1Vhb2As/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container1Vhb2As.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container1Vhb2As\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container1Vhb2As\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '1Vhb2As',
    'container.build_id' => 'a26e948b',
    'container.build_time' => 1564950541,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1Vhb2As');
