<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVOzYbNE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVOzYbNE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVOzYbNE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVOzYbNE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVOzYbNE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VOzYbNE',
    'container.build_id' => '0dba8698',
    'container.build_time' => 1565005349,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVOzYbNE');
