<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOBi3Qct\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOBi3Qct/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOBi3Qct.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOBi3Qct\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOBi3Qct\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'OBi3Qct',
    'container.build_id' => '529ec466',
    'container.build_time' => 1565047642,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOBi3Qct');
